[package]
name = "staging-face-crypto"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
ampc-secret-sharing = { git = "https://github.com/worldcoin/ampc-common.git", rev = "3062538f0307471ed0dd2be8258952c807747141" }
oxide = { git = "https://github.com/worldcoin/oxide.git", rev = "329274a32be02be0bb39ca02adc4e4e4e438ada0" }
tokio = { version = "1", features = ["rt-multi-thread", "macros", "time"] }
crypto_box = { version = "0.9.1", features = ["seal"] }
base64 = "0.22"
rand = "0.8"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
anyhow = "1"
world-id-primitives = "=0.14.0"
ark-babyjubjub = { package = "taceo-ark-babyjubjub", version = "0.5" }

[profile.dev]
opt-level = 2
