import type {
  AuthenticatorUiDetailCodeV1,
  AuthenticatorUiStateIdV1,
} from "./authenticator-ui-flow-v1";

export interface AuthenticatorUiCopyV1 {
  readonly heading: string;
  readonly body: string;
  readonly primaryAction: string | null;
  readonly secondaryAction: string | null;
}

const copy = (
  heading: string,
  body: string,
  primaryAction: string | null = null,
  secondaryAction: string | null = null,
): AuthenticatorUiCopyV1 => Object.freeze({ heading, body, primaryAction, secondaryAction });

export const AUTHENTICATOR_UI_STAGING_BANNER_V1 =
  "Staging demo · No biometric verification" as const;

export const AUTHENTICATOR_UI_COPY_V1: Readonly<
  Record<AuthenticatorUiStateIdV1, AuthenticatorUiCopyV1>
> = Object.freeze({
  request_checking: copy("Checking request", "Please wait while this staging request is checked."),
  request_review: copy(
    "Camera-flow demo for Zoom",
    "This staging demo does not verify a person or issue a Selfie Check credential. Camera images stay on this device.",
    "Continue",
    "Cancel",
  ),
  request_invalid: copy("Request not valid", "Close this tab, then start a new staging request from the app.", "Close"),
  request_expired: copy("Request expired", "Close this tab, then start a new staging request from the app.", "Close"),
  request_return_target_invalid: copy("Cannot return safely", "The staging return destination was not approved.", "Close"),
  request_rp_identity_unavailable: copy("App details unavailable", "The requesting app could not be matched to an approved presentation.", "Close"),
  admission_checking: copy("Checking this browser", "No camera or authenticator operation has started."),
  admission_safari_candidate: copy("Safari can try this demo", "Continue to the staging authenticator step.", "Continue"),
  admission_chrome_candidate: copy("Chrome can try this demo", "Continue to the staging authenticator step.", "Continue"),
  admission_handoff_required: copy("Open in Safari or Chrome", "Continue in a normal browser tab before any sensitive operation starts.", "Open browser", "Cancel"),
  admission_handoff_departing: copy("Opening browser", "A fresh staging challenge will be created after navigation."),
  admission_handoff_failed: copy("Browser could not open", "Close this tab and try the handoff again from the app.", "Close"),
  admission_update_required: copy("Update iOS to continue", "This first demo supports iOS 18 or later in a normal Safari or Chrome tab.", "Close"),
  admission_unsupported: copy("Device not supported", "This first staging demo runs only on supported iPhone browsers.", "Close"),
  admission_insecure: copy("Secure page required", "Open the approved secure staging page to continue.", "Close"),
  admission_framed: copy("Open the page directly", "This staging flow cannot run inside another page.", "Close"),
  admission_private: copy("Use a normal browser tab", "Private or unknown browsing contexts are not admitted in this first demo.", "Close"),
  admission_pwa: copy("Use Safari or Chrome", "Installed web-app mode is not admitted in this first demo.", "Close"),
  admission_unknown: copy("Browser support unknown", "This context cannot safely enter the staging flow.", "Close"),
  demo_authenticator_intro: copy(
    "Try the authenticator step",
    "This staging demo uses an injected authenticator. It does not create a passkey, evaluate PRF, or create a World ID.",
    "Continue with demo authenticator",
    "Cancel",
  ),
  session_creating: copy("Starting staging session", "The server is creating an expiring simulator session."),
  demo_authenticator_pending: copy("Starting demo authenticator", "No WebAuthn or PRF operation is running."),
  session_completing_authenticator: copy("Completing demo step", "The server is checking the staging-only completion handle."),
  demo_authenticator_ready: copy("Demo authenticator ready", "No passkey, PRF result, or World ID was created.", "Continue to camera"),
  demo_authenticator_non_completion: copy("Demo authenticator not completed", "Try again to continue the staging workflow.", "Try again", "Cancel"),
  demo_authenticator_unavailable: copy("Demo authenticator unavailable", "This staging demo cannot continue in this context.", "Return to app"),
  demo_authenticator_interrupted: copy("Demo authenticator interrupted", "Try the staging step again.", "Try again", "Cancel"),
  demo_authenticator_transport_failure: copy("Connection interrupted", "Check the authoritative staging status before retrying.", "Check status", "Cancel"),
  demo_authenticator_invalid_response: copy("Demo response not valid", "The staging flow stopped safely.", "Return to app"),
  session_reconciling: copy("Checking staging status", "The server is resolving the last operation without repeating it."),
  session_error: copy("Staging status unknown", "The last operation may have completed. Check the server status before continuing.", "Check status", "Cancel"),
  capture_policy_loading: copy("Preparing camera step", "Loading the provisional staging capture policy."),
  capture_intro: copy(
    "Try the camera step",
    "Use your camera to collect local frame metadata for this staging workflow. No biometric or uniqueness check is performed.",
    "Start camera demo",
    "Cancel",
  ),
  capture_permission_request: copy("Allow camera access", "The browser will ask for camera access. Camera images stay on this device."),
  capture_acquiring: copy("Starting camera", "Waiting for the user-facing camera."),
  capture_preparing: copy("Preparing preview", "Waiting for the first local frame."),
  capture_preview: copy("Camera ready", "Place your face in the oval, then hold steady.", "Collect frame metadata", "Cancel"),
  capture_guidance_adjust: copy("Adjust the camera view", "Follow the local capture guidance, then try again.", "Try again", "Cancel"),
  capture_guidance_retake: copy("Retake the capture", "The local image was not clear enough for this capture attempt.", "Retake", "Cancel"),
  capture_guidance_unavailable: copy("Visual guidance unavailable", "You can continue only through the approved guidance-free staging path.", "Continue without guidance", "Cancel"),
  capture_sampling: copy("Camera ready, hold steady", "Collecting local frame metadata. This is not biometric verification."),
  capture_artifact_ready: copy("Frame metadata ready", "Camera pixels will be cleared before only metadata and digests are submitted."),
  capture_cleaning: copy("Closing camera", "Stopping camera tracks and clearing transient frame buffers."),
  capture_complete: copy("Capture complete", "Only the approved metadata and digests are ready for the staging simulator."),
  capture_error: copy("Camera step stopped", "The capture ended safely. Review the reason and try an allowed next step.", "Try again", "Cancel"),
  biometric_simulation_pending: copy("Running staging scenario", "The server-selected simulator is processing workflow metadata. No biometric model is running."),
  biometric_simulated_pass: copy("Pass scenario returned", "This is a server-selected simulator result. No biometric check ran."),
  biometric_simulated_reject: copy("Reject scenario returned", "This staging result does not mean a spoof or person was detected.", "Return to app"),
  biometric_simulated_retry: copy("Retry scenario returned", "Start a new local capture attempt in the same unexpired staging session.", "Retake", "Cancel"),
  biometric_simulated_unavailable: copy("Simulator unavailable", "Check status or retry the same staging operation without assuming success.", "Retry", "Cancel"),
  issuance_simulation_pending: copy("Creating staging artifact", "The issuance simulator is creating a non-production workflow artifact."),
  issuance_simulated_reject: copy("Issuance scenario rejected", "No credential or proof was issued.", "Return to app"),
  issuance_simulated_unavailable: copy("Issuance simulator unavailable", "Check status or retry the same staging operation without assuming success.", "Retry", "Cancel"),
  simulated_credential_ready: copy(
    "Staging demo complete",
    "A non-production workflow artifact was created. No biometric verification or uniqueness check was performed. It is not a Selfie Check credential.",
    "Return to app",
  ),
  return_redirecting: copy("Returning to app", "The server-approved return action is in progress."),
  return_callback_failed: copy("Could not return", "The staging result remains unchanged. Try the server-approved return action again.", "Try again", "Close"),
  returned: copy("Returned", "The staging flow is complete."),
  flow_cancelling: copy("Cancelling", "Stopping active work and clearing transient data."),
  flow_cancelled: copy("Demo cancelled", "Camera tracks and transient data were cleared.", "Close"),
  flow_closed: copy("You can close this tab", "No session-bound return action was used."),
  flow_expired: copy("Session expired", "Close this tab and start a new staging session from the app.", "Close"),
  flow_failed: copy("Demo stopped safely", "No success was assumed. Close this tab and start again from the app.", "Close"),
});

export const AUTHENTICATOR_UI_DETAIL_COPY_V1: Readonly<
  Record<AuthenticatorUiDetailCodeV1, string>
> = Object.freeze({
  face_not_found: "Move into the camera view.",
  multiple_faces: "Keep only one face in the camera view.",
  move_closer: "Move closer to the camera.",
  move_farther: "Move farther from the camera.",
  center_face: "Center your face in the oval.",
  improve_lighting: "Move to brighter, even lighting.",
  reduce_lighting: "Move away from very bright light.",
  image_blurry: "Hold the device steady and retake the capture.",
  camera_inactive: "The camera is not active.",
  camera_unavailable: "The camera is unavailable.",
  face_guidance_unavailable: "Face-count guidance is unavailable.",
  framing_guidance_unavailable: "Framing guidance is unavailable.",
  lighting_guidance_unavailable: "Lighting guidance is unavailable.",
  sharpness_guidance_unavailable: "Sharpness guidance is unavailable.",
  retake_limit_reached: "The staging retake limit was reached.",
  policy_invalid: "The staging quality policy is not valid.",
  quality_input_invalid: "The local quality input is not valid.",
  unsupported_context: "This browser context cannot start the camera step.",
  prf_not_ready: "The staging compatibility gate is not ready.",
  user_activation_required: "Tap the camera button to start.",
  permission_denied: "Camera permission was not granted.",
  camera_busy: "Another app or page may be using the camera.",
  camera_restricted: "Camera access is restricted on this device.",
  camera_unsupported: "This browser does not expose the required camera API.",
  non_user_facing_camera: "A user-facing camera was not available.",
  constraints_unsatisfied: "The requested camera settings were unavailable.",
  acquisition_aborted: "Camera startup was interrupted.",
  permission_timeout: "The camera permission request timed out.",
  preview_timeout: "The first camera frame did not arrive in time.",
  preview_invalid_frame: "The camera returned an invalid frame.",
  interrupted: "The active step was interrupted.",
  session_expired: "The staging session expired.",
  capture_in_progress: "A capture attempt is already running.",
  artifact_limit: "The capture exceeded the provisional staging limits.",
  quality_callback_failed: "Local capture guidance failed safely.",
  unknown: "An unknown local capture error occurred.",
  gateway_disabled: "The staging gateway is disabled.",
  invalid_request: "The staging request was not valid.",
  body_too_large: "The staging request exceeded its size limit.",
  unauthorized: "The staging request could not be authenticated.",
  origin_forbidden: "This origin is not approved for the staging flow.",
  not_found: "The staging session was not found.",
  expired: "The staging session expired.",
  invalid_state: "The staging operation is not allowed in the current state.",
  binding_mismatch: "The operation did not match the existing staging request.",
  replay_rejected: "The staging operation was already consumed.",
  artifact_invalid: "The frame metadata did not match the staging policy.",
  resource_busy: "The staging service is busy.",
  network_unavailable: "The network is unavailable.",
  network_timeout: "The staging request timed out.",
  response_invalid: "The staging response was not valid.",
  return_target_invalid: "The return destination was not approved.",
  navigation_blocked: "The browser blocked the return action.",
  navigation_failed: "The return action failed.",
  safe_internal_error: "The staging demo stopped safely.",
});

// Copy is intentionally explicit about negative assurance. Figma text that says
// real person, liveness, or real passkey/Selfie Check success is not used here.
